<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Resources</name>
   <tag></tag>
   <elementGuidId>4667757f-8a6d-4610-aefe-05475c041bee</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-header</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Resources</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js wf-proximanova-n7-active wf-proximanova-n1-active wf-proximanova-n6-active wf-proximanova-n4-active wf-museosans-n1-active wf-museosans-n3-active wf-museosans-i3-active wf-museosans-n5-active wf-museosans-i5-active wf-museosans-n7-active wf-museosans-i7-active wf-ffdinwebcondensed-n7-active wf-ffdinwebcondensed-n6-active wf-garamondpremierpro-n4-active wf-garamondpremierpro-i4-active wf-garamondpremierpro-n7-active wf-garamondpremierpro-i7-active wf-garamondpremierpro-n5-active wf-brandongrotesque-n4-active wf-brandongrotesque-i4-active wf-brandongrotesque-n7-active wf-brandongrotesque-i7-active wf-active&quot;]/body[@class=&quot;html not-front not-logged-in no-sidebars page-resources navbar-is-static-top eu-cookie-compliance-processed&quot;]/div[@class=&quot;main-container container&quot;]/div[@class=&quot;row&quot;]/section[@class=&quot;col-sm-12&quot;]/h1[@class=&quot;page-header&quot;]</value>
   </webElementProperties>
</WebElementEntity>
