<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TotalwasteAvg</name>
   <tag></tag>
   <elementGuidId>8d1d16c9-83ce-44df-88b6-1b3510ee7b0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//section[@id='performance_report']/div[4]/div[2]/table/tbody/tr[4]/th[2]/span)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
