<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TotalEngAvg</name>
   <tag></tag>
   <elementGuidId>f5b90306-f8f8-4615-891b-64d2f1f7b343</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//section[@id='performance_report']/div[2]/div[2]/table/tbody/tr[4]/th[2]/span)[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
