<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TotalwaterAvg</name>
   <tag></tag>
   <elementGuidId>10bf585a-e6ec-4d04-ab21-e49358562eb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//section[@id='performance_report']/div[3]/div[2]/table/tbody/tr[4]/th[2]/span)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
