<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TWaterLocalAvg</name>
   <tag></tag>
   <elementGuidId>888a2e20-5eff-467a-bb0e-3d5cb0c4e035</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//section[@id='performance_report']/div[3]/div[2]/table/tbody/tr[3]/th)[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
