<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>prjAddress</name>
   <tag></tag>
   <elementGuidId>ae6bfc9d-9ecc-4447-b22d-f85d845027fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>//textarea[@name=&quot;project_address&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name=&quot;project_address&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
