<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CACitesOtherSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>9975ffb8-f1ab-4fc8-bc2d-229f0069a12f</testSuiteGuid>
   <testCaseLink>
      <guid>798419fb-d5e0-4121-8f76-9c3b6d12ef8d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MyCities/CitiesOther/AddNewProjectTest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8dd84820-cc78-431f-8d88-9f8fa570c820</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>148121b8-7542-4d53-92e7-0950107bd446</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>004a71f5-2958-4d56-9ba9-1ef0d9880fca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1f1cc0a9-001a-44d4-a16e-4302a94d2147</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MyCities/CitiesOther/RegPaymentByCreditCardTest</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f86580b3-ddf4-4d5e-acd7-da182a0e5001</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MyCities/CitiesOther/INTPerformanceScoreRevPayByCheckTest</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
