<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_datainput-widget</name>
   <tag></tag>
   <elementGuidId>ba35d0ac-ee0f-43af-8ce4-843d6ed0f33b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datainput-widget</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>https://api.usgbc.org/qas/leed/assets/LEED:1000078491/widget/meter/?access-token=jVc5p2Ws2JJWYou2VwMIfk1fT0kttF&amp;subscription-key=5a41833022f046dc951383ead38d16d3&amp;type=all&amp;version=1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.usgbc.org/qas/leed/assets/LEED:1000078491/widget/meter/?access-token=jVc5p2Ws2JJWYou2VwMIfk1fT0kttF&amp;subscription-key=5a41833022f046dc951383ead38d16d3&amp;type=all&amp;version=1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>851px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datainput-widget&quot;)</value>
   </webElementProperties>
</WebElementEntity>
