<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SpaceType</name>
   <tag></tag>
   <elementGuidId>2901fc8d-6a44-44e2-97b9-6b9bce0fd711</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>formdata.spaceType</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>spaceType</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-not-empty</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Airport: Control TowerAirport: Distribution CenterAirport: HangarAirport: OfficeAirport: OtherAirport: Public Order/Fire/PoliceAirport: Rental Car CenterAirport: Terminal/ConcourseAirport: Vehicle Service/RepairCirculation SpaceCore Learning Space: College/UniversityCore Learning Space: K-12 Elementary/Middle SchoolCore Learning Space: K-12 High SchoolCore Learning Space: Other classroom educationCore Learning Space: Preschool/DaycareData CenterHealthcare: Clinic/Other OutpatientHealthcare: InpatientHealthcare: Nursing Home/ Assisted LivingHealthcare: Outpatient Office (Diagnostic)Industrial ManufacturingLaboratoryLodging: DormitoryLodging: Hotel/Motel/Resort, Full ServiceLodging: Hotel/Motel/Resort, Limited ServiceLodging: Hotel/Motel/Resort, Select ServiceLodging: InnLodging: Other lodgingMulti-Family Residential: ApartmentMulti-Family Residential: CondominiumMulti-Family Residential: LowriseOffice: Administrative/ProfessionalOffice: FinancialOffice: GovernmentOffice: Medical (Non-Diagnostic)Office: Mixed-UseOffice: Other OfficePublic Assembly: Convention CenterPublic Assembly: EntertainmentPublic Assembly: LibraryPublic Assembly: Other AssemblyPublic Assembly: RecreationPublic Assembly: Social/MeetingPublic Assembly: Stadium/ArenaPublic Order and Safety: Fire/Police StationPublic Order and Safety: Other Public OrderReligious WorshipRetail: Bank BranchRetail: Convenience StoreRetail: Enclosed MallRetail: Fast FoodRetail: Grocery Store/Food MarketRetail: Open Shopping CenterRetail: Other RetailRetail: Restaurant/CafeteriaRetail: Vehicle DealershipService: Other ServiceService: Post Office/Postal CenterService: Repair ShopService: Vehicle Service/RepairService: Vehicle Storage/MaintenanceSingle family home (attached)Single family home (detached)Transit: DepotTransit: LineTransit: Maintenance/StorageTransit: OfficeTransit: OtherTransit: StationTransit: Station/ElevatedTransit: Station/Open Air Ground LevelTransit: Station/UndergroundTransit: SystemWarehouse: Nonrefrigerated Distribution/ShippingWarehouse: RefrigeratedWarehouse: Self Storage UnitsWarehouse: GeneralOther</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;row ng-scope&quot;]/main[@class=&quot;view-animate fade-up overflow_y_initial full-screen-row ng-scope&quot;]/div[@class=&quot;flex ng-scope&quot;]/div[@class=&quot;payment-new-content&quot;]/div[@class=&quot;mb25 ng-scope&quot;]/div[@class=&quot;payment-card ng-scope&quot;]/div[@id=&quot;details-form&quot;]/table[@class=&quot;width-100-perc&quot;]/tbody[@class=&quot;table-margin-20&quot;]/tr[@class=&quot;ng-scope&quot;]/td[@class=&quot;pt30&quot;]/div[@class=&quot;select-group group&quot;]/select[@class=&quot;ng-pristine ng-untouched ng-valid ng-not-empty&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//select[@name='spaceType']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='details-form']/table/tbody/tr[2]/td[2]/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Space Type'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Project Details'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Owner Type'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Owner Organization'])[1]/preceding::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//select</value>
   </webElementXpaths>
</WebElementEntity>
