<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GoogleDrive.pdf</name>
   <tag></tag>
   <elementGuidId>50a6aec4-2430-4566-b6e5-6e510e8c08c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[(text() = 'Agreement.pdf' or . = 'Agreement.pdf') and @ref_element = 'Object Repository/DataInput/DataInputFileUpload/UploadFilesViaCloud/iframe_GoogleDrive']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'GoogleDrive.pdf' or . = 'GoogleDrive.pdf')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qj-bl-Oc-tc</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agreement.pdf</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:10.DoclistBlob.0.18hTsJSF4JM-QEaPlp0PuH76y61qnuffl:label&quot;)/div[@class=&quot;qj-Rl-bl-Oc&quot;]/div[@class=&quot;qj-Rl-cb&quot;]/span[@class=&quot;qj-bl-Oc-tc&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/DataInput/DataInputFileUpload/UploadFilesViaCloud/iframe_GoogleDrive</value>
   </webElementProperties>
</WebElementEntity>
