<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_GoogleDrive</name>
   <tag></tag>
   <elementGuidId>aba48596-c9f5-4954-af11-95e6943a076c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@tabindex = '0']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;picker-frame picker-dialog-frame&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nvg259jlj4m1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nvg259jlj4m1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>picker-frame picker-dialog-frame</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>camera</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://docs.google.com/picker?protocol=gadgets&amp;origin=https%3A%2F%2Fstg.app.arconline.io&amp;oauth_token=ya29.GlvzBSR-v8o5YAUMq_V5nPJT_GaPiXajxRWD9WUX0y2Iz-g0vsAkkX49J5P1rVCyqDO3Es-k9gZIoPCaoQUsNIhhP_qT85oS6vxEaRfR50c_6W90QQjVDK3Biu0I&amp;developerKey=AIzaSyDwZV5TZd3xjoXmo_-26kent98c4oEugw8&amp;hostId=stg.app.arconline.io&amp;relayUrl=https%3A%2F%2Fstg.app.arconline.io%2Ffavicon.ico&amp;nav=((%22all%22))&amp;rpctoken=ucl5mafn1lmg&amp;rpcService=nvg259jlj4m1&amp;thirdParty=true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nvg259jlj4m1&quot;)</value>
   </webElementProperties>
</WebElementEntity>
