<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OneDriveSelectFile</name>
   <tag></tag>
   <elementGuidId>9e51df39-ebdc-439c-b296-1a91b226e9a2</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon-name</name>
      <type>Main</type>
      <value>StatusCircleCheckmark</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Check-check check-75</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appRoot&quot;)/div[@class=&quot;od-FilePicker&quot;]/div[@class=&quot;od-FilePicker-picker&quot;]/div[@class=&quot;od-ItemPicker od-ItemPicker--hasBranding od-ItemPicker--hasActions od-ItemPicker--hasCommandBar&quot;]/div[@class=&quot;od-ItemPicker-selector&quot;]/div[@class=&quot;od-FilePicker-content&quot;]/div[@class=&quot;od-FilePicker-innerContent&quot;]/div[@class=&quot;od-FolderItemContent od-ItemContent&quot;]/div[@class=&quot;od-FolderItemContent-list od-ItemContent-list&quot;]/div[@class=&quot;od-TilesList&quot;]/div[@class=&quot;ms-Fabric root-64&quot;]/div[@class=&quot;root-65&quot;]/div[@class=&quot;ms-SelectionZone&quot;]/div[@class=&quot;ms-FocusZone ms-TilesList&quot;]/div[@class=&quot;ms-List&quot;]/div[@class=&quot;ms-List-surface&quot;]/div[@class=&quot;ms-List-page listPage_4aa03851&quot;]/div[@class=&quot;ms-TilesList-grid grid_4aa03851&quot;]/div[@class=&quot;ms-List-cell listCell_4aa03851 ms-TilesList-cell--firstInRow cellFirstInRow_4aa03851&quot;]/div[@class=&quot;cell_4aa03851&quot;]/div[@class=&quot;cellContent_4aa03851&quot;]/div[@class=&quot;ms-Tile od-ItemTile2 od--hasContextMenu od-ItemTile2--isLarge tile_04bd1798 ms-Tile--isLarge isLarge_04bd1798 ms-Tile--hasForegroundFrame hasForegroundFrame_04bd1798 ms-Tile--isSelectable selectable_04bd1798 ms-Tile--showBackground showBackground_04bd1798 ms-Tile--invokable invokable_04bd1798&quot;]/span[@class=&quot;ms-Tile-check check_04bd1798 checkHost_904a6025&quot;]/div[@class=&quot;ms-Check root-70&quot;]/i[@class=&quot;ms-Check-check check-75&quot;]</value>
   </webElementProperties>
</WebElementEntity>
