<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>projectWebsite</name>
   <tag></tag>
   <elementGuidId>7d04898e-d8d6-46a7-937f-1e61ee3dd8a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='manage-project-details']/tbody/tr[19]/td[2]/input</value>
   </webElementProperties>
</WebElementEntity>
