<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tellAboutProject</name>
   <tag></tag>
   <elementGuidId>bc42680d-0847-4d7c-84be-532c0273a70d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='manage-project-details']/tbody/tr[20]/td[2]/textarea</value>
   </webElementProperties>
</WebElementEntity>
