<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Attempted</name>
   <tag></tag>
   <elementGuidId>08c4b2f8-9b24-45e0-b973-3d5a74a3c128</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Attempted</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actions-form&quot;)/div[@class=&quot;col-md-4 ng-scope&quot;]/section[@class=&quot;widget&quot;]/div[@class=&quot;widget-body&quot;]/div[@class=&quot;mt20&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;dropdown display-inline ml10 open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[1]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
