<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_datainput-widget</name>
   <tag></tag>
   <elementGuidId>c15aea50-a4a7-40b7-aed6-cb8766cbc34f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@id = 'datainput-widget']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datainput-widget</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>https://api.usgbc.org/qas/leed/assets/LEED:1000076629/widget/meter/?access-token=sq2qaB0L3c50L2TgF51VbEVjCXslsW&amp;subscription-key=5a41833022f046dc951383ead38d16d3&amp;type=all&amp;version=1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.usgbc.org/qas/leed/assets/LEED:1000076629/widget/meter/?access-token=sq2qaB0L3c50L2TgF51VbEVjCXslsW&amp;subscription-key=5a41833022f046dc951383ead38d16d3&amp;type=all&amp;version=1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>700px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datainput-widget&quot;)</value>
   </webElementProperties>
</WebElementEntity>
