<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>No</name>
   <tag></tag>
   <elementGuidId>8de2fdfb-6400-4ec9-8cd6-43ea74e23eca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@ng-click=&quot;registerLEEDOrNonLEED('no')&quot;]/span[@class=&quot;radiobtn&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
