<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Thank</name>
   <tag></tag>
   <elementGuidId>b40ba1eb-c54c-40ab-90d0-96fb57fd6393</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>(//*[@data-ng-click=&quot;reloadPage()&quot;])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;app&quot;)/section[@class=&quot;surveyPage widget ng-scope&quot;]/div[@class=&quot;modal fade overlapDates in&quot;]/div[@class=&quot;modal-dialog modal-sm hidden-xs hidden-md hidden-sm&quot;]/div[@class=&quot;modal-content p50 modal_radius&quot;]/div[@class=&quot;mt30 align-center&quot;]/input[@id=&quot;dismiss_overlapDates&quot;][count(. | //input[@id = 'dismiss_overlapDates']) = count(//input[@id = 'dismiss_overlapDates'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@ng-if=&quot;satisfaction != 0&quot;]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dismiss_overlapDates</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>reloadPage()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>OK</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn action-button btnGreen ccc_border</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/section[@class=&quot;surveyPage widget ng-scope&quot;]/div[@class=&quot;modal fade overlapDates in&quot;]/div[@class=&quot;modal-dialog modal-sm hidden-xs hidden-md hidden-sm&quot;]/div[@class=&quot;modal-content p50 modal_radius&quot;]/div[@class=&quot;mt30 align-center&quot;]/input[@id=&quot;dismiss_overlapDates&quot;]</value>
   </webElementProperties>
</WebElementEntity>
