<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ExtremelySatisfySpanText</name>
   <tag></tag>
   <elementGuidId>61a8a898-809c-424a-aa97-ce01334b8c4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>//*[@id=&quot;app&quot;]/section/div[8]/div[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/section/div[8]/div[4]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
