<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_French</name>
   <tag></tag>
   <elementGuidId>0a7a9268-38e2-4a73-9fc4-6875efa52986</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>//*[@ng-click=&quot;copyLink('fr')&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@ng-click=&quot;emailSurvey('fr')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>French</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sideNavContainer&quot;)/md-content[@class=&quot;menu-wrapper layout-padding&quot;]/div[@class=&quot;meterContent-wrapper survey_charts_wrapper ng-scope&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 pl0&quot;]/div[@class=&quot;hidden-xs hidden-sm col-md-3 survey-response&quot;]/div[@class=&quot;dropdown email-dropdown open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[@class=&quot;language_unit&quot;]/div[@class=&quot;left-right-align&quot;]/span[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/DataInput/Language/iframe_Data Input_datainput-wi</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='sideNavContainer']/md-content/div[2]/div[2]/div/div[2]/div[2]/ul/li[2]/div/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[2]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portuguese'])[2]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='German'])[2]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[2]/ul/li[2]/div/span</value>
   </webElementXpaths>
</WebElementEntity>
