<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>PromocodeSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>120</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>4169a172-fa04-46ea-9937-3078ea005da1</testSuiteGuid>
   <testCaseLink>
      <guid>ae0d921a-4d0e-4232-9d15-2798e22198f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promocode/Building/BuildingNone/AddNewProjectTest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a40be801-9796-4545-bebc-49c1432e2b5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f40d3df4-b09a-47a3-ab95-828a9ae95eb0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3de3877-cde4-4bbf-b066-12c907b61c5f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>474102fb-d6e9-4efa-9c3c-1a83c8709341</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promocode/Building/BuildingNone/PaymentByCreditCardWithFiftyPercentPromoTest</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>2414d935-8ba9-4f29-95d7-21c95b2aa3ba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promocode/Building/BuildingNone/AddNewProjectTest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a40be801-9796-4545-bebc-49c1432e2b5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f40d3df4-b09a-47a3-ab95-828a9ae95eb0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3de3877-cde4-4bbf-b066-12c907b61c5f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7be8a432-6c27-47d7-90ef-b674db90a19f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Promocode/Building/BuildingNone/PaymentByCreditCardWithHundredPercentPromoTest</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
