<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>anticipatedType</name>
   <tag></tag>
   <elementGuidId>a7768968-a073-4cd1-8dfa-5e588cf50965</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>span5 required</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>anticipatedType</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>anticipatedType</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select project typeAirport: Control TowerAirport: Distribution CenterAirport: HangarAirport: OfficeAirport: OtherAirport: Public Order/Fire/PoliceAirport: Rental Car CenterAirport: Terminal/ConcourseAirport: Vehicle Service/RepairCirculation SpaceCore Learning Space: College/UniversityCore Learning Space: K-12 Elementary/Middle SchoolCore Learning Space: K-12 High SchoolCore Learning Space: Other classroom educationCore Learning Space: Preschool/DaycareData CenterHealthcare: Clinic/Other OutpatientHealthcare: InpatientHealthcare: Nursing Home/ Assisted LivingHealthcare: Outpatient Office (Diagnostic)Industrial ManufacturingLaboratoryLodging: DormitoryLodging: Hotel/Motel/Resort, Full ServiceLodging: Hotel/Motel/Resort, Limited ServiceLodging: Hotel/Motel/Resort, Select ServiceLodging: InnLodging: Other lodgingMulti-Family Residential: ApartmentMulti-Family Residential: CondominiumMulti-Family Residential: LowriseOffice: Administrative/ProfessionalOffice: FinancialOffice: GovernmentOffice: Medical (Non-Diagnostic)Office: Mixed-UseOffice: Other OfficePublic Assembly: Convention CenterPublic Assembly: EntertainmentPublic Assembly: LibraryPublic Assembly: Other AssemblyPublic Assembly: RecreationPublic Assembly: Social/MeetingPublic Assembly: Stadium/ArenaPublic Order and Safety: Fire/Police StationPublic Order and Safety: Other Public OrderReligious WorshipRetail: Bank BranchRetail: Convenience StoreRetail: Enclosed MallRetail: Fast FoodRetail: Grocery Store/Food MarketRetail: Open Shopping CenterRetail: Other RetailRetail: Restaurant/CafeteriaRetail: Vehicle DealershipService: Other ServiceService: Post Office/Postal CenterService: Repair ShopService: Vehicle Service/RepairService: Vehicle Storage/MaintenanceSingle family home (attached)Single family home (detached)Transit: DepotTransit: LineTransit: Maintenance/StorageTransit: OfficeTransit: OtherTransit: StationTransit: Station/ElevatedTransit: Station/Open Air Ground LevelTransit: Station/UndergroundTransit: SystemWarehouse: GeneralWarehouse: Nonrefrigerated Distribution/ShippingWarehouse: RefrigeratedWarehouse: Self Storage UnitsOther</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anticipatedType&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//select[@id='anticipatedType']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//form[@id='project-registration']/fieldset/div/div[9]/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anticipated type'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End date'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is the station'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is the annual ridership for this station?'])[1]/preceding::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[9]/div/select</value>
   </webElementXpaths>
</WebElementEntity>
