<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RatingSystem</name>
   <tag></tag>
   <elementGuidId>baecc3fb-3d2d-42f0-a299-e36225ef6448</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id = 'ratingsystem' and @name = 'ratingsystem' or @id = 'ratingSystem' and @name = 'ratingSystem']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//select[@id = 'ratingsystem' and @name = 'ratingsystem']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ratingsystem</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ratingsystem</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>span5 required</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LEED v4 BD+C: New ConstructionLEED v4 BD+C: Core and ShellLEED v4 BD+C: SchoolsLEED v4 BD+C: RetailLEED v4 BD+C: HealthcareLEED v4 BD+C: Data CentersLEED v4 BD+C: HospitalityLEED v4 BD+C: Warehouses and Distribution CentersLEED v4 BD+C: TransitLEED v4 ID+C: Commercial InteriorsLEED v4 ID+C: RetailLEED v4 ID+C: HospitalityLEED v4 O+M: Existing BuildingsLEED v4 O+M: Data CentersLEED v4 O+M: Warehouses and Distribution CentersLEED v4 O+M: HospitalityLEED v4 O+M: SchoolsLEED v4 O+M: RetailLEED v4 O+M: MultifamilyLEED v4.1 BD+C: New ConstructionLEED v4.1 BD+C: Core and ShellLEED v4.1 BD+C: SchoolsLEED v4.1 BD+C: RetailLEED v4.1 BD+C: HealthcareLEED v4.1 BD+C: Data CentersLEED v4.1 BD+C: HospitalityLEED v4.1 BD+C: Warehouses and Distribution CentersLEED v4.1 ID+C: Commercial InteriorsLEED V4.1 ID+C: RetailLEED v4.1 ID+C: HospitalityLEED v4.1 O+M: Existing BuildingsLEED v4.1 O+M: InteriorsOther</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ratingsystem&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//select[@id='ratingsystem']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//form[@id='project-registration']/fieldset/div/div[4]/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rating system'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of buildings'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email GBCI'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[4]/div/select</value>
   </webElementXpaths>
</WebElementEntity>
