<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CNCitiesNoneTestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f495d5e2-ae31-42c2-b5d2-88015b9f0f5d</testSuiteGuid>
   <testCaseLink>
      <guid>b2e59bbe-56df-4b47-90b5-86af44026815</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MyCities/CitiesNone/AddNewProjectTest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a2a89b6-4382-43d0-b209-b6aa3d8270ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e18d002a-b205-48b9-8089-17f350be102b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53444a73-94c9-454e-9bf8-60215884c3c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>abeac8bc-99e4-4bfe-8fc6-8d82aed36d39</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MyCities/CitiesNone/CNRegPaymentByCheckTest</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
