<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProjectButton</name>
   <tag></tag>
   <elementGuidId>daa40824-23de-4018-a58c-46600c9bc16b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.active:nth-child(2)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[text()=&quot;Projects&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
