<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FileUploadInput</name>
   <tag></tag>
   <elementGuidId>91b3768b-6545-4447-b80f-c590ee3fe67d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='file'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[type='file']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/DataInput/iframe_datainput-widget</value>
   </webElementProperties>
</WebElementEntity>
