<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Energy</name>
   <tag></tag>
   <elementGuidId>78b8b6e1-9a37-4356-9322-79311433e92d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;sideNavContainer&quot;]/md-sidenav/div/table/tbody[1]/tr[2]/td[2]/div/text()</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
