<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_End User License Agreement</name>
   <tag></tag>
   <elementGuidId>3247b69c-3c5e-4911-b426-40a0db5add3d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>policy-link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/useragreement</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>End User License Agreement</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)/form[@id=&quot;user-login&quot;]/div[1]/div[@class=&quot;panel panel-default user-login-tpl-page&quot;]/div[@class=&quot;panel-body&quot;]/div[@id=&quot;user-login-block-container&quot;]/div[@id=&quot;user-login-block-form-fields&quot;]/div[@class=&quot;form-type-checkbox form-item-field-policy-accept form-item checkbox&quot;]/label[1]/a[@class=&quot;policy-link&quot;]</value>
   </webElementProperties>
</WebElementEntity>
