<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>termsarcskoru</name>
   <tag></tag>
   <elementGuidId>2e86405e-0437-4570-a12b-d634093faa0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>//*[text()='www.arcskoru.com']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[text()='www.arcskoru.com']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = 'https://www.arcskoru.com/' and (text() = 'www.arcskoru.com' or . = 'www.arcskoru.com')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.arcskoru.com/</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>www.arcskoru.com</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-system-main&quot;)/div[@class=&quot;about-wrapper&quot;]/div[@class=&quot;field field-name-body field-type-text-with-summary field-label-hidden&quot;]/div[@class=&quot;field-items&quot;]/div[@class=&quot;field-item even&quot;]/div[@class=&quot;content-container&quot;]/p[6]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
